project:
  type: website
  output-dir: docs

filters:
  - shinylive

website:
  title: "LittleMonkeyLab Shiny Apps"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Apps
        menu:
          - href: apps/sliders/index.qmd
            text: Sliders Demo
      - text: Slides
        menu:
          - text: (Coming soon)
            href: "#"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
